#!/usr/bin/env python3
"""Generate the embedded 120x120 monochrome boot logo."""

import argparse
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "src" / "images" / "crossfish.png"
DEFAULT_OUTPUT = ROOT / "src" / "images" / "Logo120.h"
WIDTH = 120
HEIGHT = 120
THRESHOLD = 128


def render_header(source: Path) -> str:
    with Image.open(source) as opened:
        image = opened.convert("RGBA")
        background = Image.new("RGBA", image.size, (255, 255, 255, 255))
        background.alpha_composite(image)
        image = background.convert("L").resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)

    # The firmware bitmap convention is rotated counter-clockwise relative to
    # the source artwork. GfxRenderer rotates coordinates but not bitmap bits.
    image = image.rotate(90, expand=False)
    pixels = image.load()
    packed: list[int] = []
    for y in range(HEIGHT):
        for x in range(0, WIDTH, 8):
            value = 0
            for bit in range(8):
                if pixels[x + bit, y] >= THRESHOLD:
                    value |= 1 << (7 - bit)
            packed.append(value)

    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "// Generated by scripts/generate_boot_logo.py from src/images/crossfish.png.",
        "// Crossfish, 120x120px, row-major 1bpp, MSB-first, white=1.",
        "// clang-format off",
        "static const uint8_t Logo120[] = {",
    ]
    for offset in range(0, len(packed), 16):
        chunk = ", ".join(f"0x{value:02x}" for value in packed[offset : offset + 16])
        lines.append(f"    {chunk},")
    lines.extend(
        [
            "};",
            "// clang-format on",
            "",
            'static_assert(sizeof(Logo120) == 1800, "Logo120 must be exactly 120x120 / 8 bytes");',
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the generated header is stale.")
    args = parser.parse_args()

    generated = render_header(args.source)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"Boot logo header is stale: {args.output}")
        print(f"Boot logo header is current: {args.output}")
        return

    args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Boot logo header written to: {args.output}")


if __name__ == "__main__":
    main()
